### ISSUE TITLE
Exposé in den Präsentationsfolien

### ISSUE THREAD

**Issue by annegermund** [verenaheissbach/EPWS2122GermundHeissbach#10]
Hallo Mario,
bei der Erstellung der Präsentationsfolien ist die Frage aufgekommen, ob wir die Inhalte unseres Exposés in den Foliennotizen des 1. Audits verwenden dürfen? Wir würden gerne Teile davon einbinden, um die Problemstellung zu schildern.
Danke im Voraus!

**Comment by mariofaske** [comment]
Hallo,

könnt ihr gerne machen, da es uns unter anderem hilft, Entscheidungen nachzuvollziehen etc. Denkt aber bitte daran, dass das Audit keinem starren Präsentationsablauf folgen wird. Das heißt, wir führen ein Fachgespräch und die Folien dienen nur als Orientierung bzw Unterstützung während dem Gespräch. Die Fragen, die wir stellen könnten/werden findet ihr unter den Kernfragen und den Fachperspektive-spezifischen Leitfragen.

**Comment by annegermund** [comment]
Super, vielen Dank für die schnelle Rückmeldung! Dann bereiten wir den Foliensatz dementsprechend vor.
