### ISSUE TITLE
Überarbeitetes Domänenmodell

### ISSUE THREAD

**Issue by annegermund** [verenaheissbach/EPWS2122GermundHeissbach#11]
Hallo Mario,
wir haben nach eurem Feedback zum Exposé unser deskriptives Domänenmodell überarbeitet. Es wäre super, wenn du dir die aktuelle Variante im Wiki im Kapitel Domänenmodelle (2. Iteration) einmal anschauen könntest!
Wir haben in dieser Variante jetzt alle Messwerte und Messverfahren detailliert aufgeführt. Hältst du es für sinnvoll, dass wir die Messwerte und die Probe als Teile-Ganzes-Relation mit einer Komposition dargestellt haben? Oder würdest du es mit Assoziationen versuchen? Hier waren wir uns nur nicht sicher, wie wir diese beschriften könnten.

Wir haben in der aktuellen Version auch zunächst die Multiplizitäten an den Assoziationen der Messwerte weggelassen. Sollten wir diese noch hinzufügen oder wäre das nicht unbedingt notwendig?

Vielen Dank vorab!

**Comment by mariofaske** [comment]
Hallo Anne,

Assoziation sind in dem Fall schwierig, da diese sich ja sehr oft wiederholen, wie man bei "nutzt" sieht. Die Teil-Ganzes-Relation finde ich so in Ordnung, da ja sonst nur ein "hat" an den Assoziationen stehen würde. 

Was macht der Betreiber wenn die Werte zu hoch oder zu niedrig sind? Besonders wenn bei der IST-Situation der Betreiber noch manuell Stoffe dem System hinzuführen oder verringern müsste, könnte ein automatisiertes System den Betreiber dahingehend unterstützen.

**Comment by annegermund** [comment]
Hallo Mario,

tatsächlich wäre die einzig sinnvolle Automatisierung in diesem Fall das Einschalten der Luftpumpe bei zu geringem Sauerstoffgehalt und das Hinzugeben von Eisen... Für alle anderen Werte kann höchstens eine Warnung ausgegeben werden, da es für die Regulation der anderen Mineralien keinen eindeutigen Lösungsweg gibt. Möglich wäre z.B., dass Wasser abgelassen wird, zusätzliche Pflanzen eingesetzt werden oder die Futtermenge erhöht wird. Das müsste aber der Betreiber am besten selbst entscheiden.

Wir würden hierfür im Domänenmodell noch zwei Assoziationen für die Luftpumpe und die Eisenzugabe zwischen Betreiber und Aquaponikanlage einfügen. Gibt es eine Möglichkeit, im Domänenmodell eine Kausalverbindung zwischen den Messwerten und den neuen Assoziationen aufzuzeigen? Oder würde es so schon ausreichen?

Eine weitere Frage zum präskriptiven Domänenmodell: Sollen wir nur unsere ausgewählten Use Cases abdecken oder die gesamte mögliche Automatisierung darstellen? Für unser Entwicklungsprojekt würden wir ja eigentlich nur den Wasserstand und die Temperatur betrachten.

**Comment by mariofaske** [comment]
Ihr könnt zusätzliche Anmerkungen mit gestrichelten Kästchen an die Assoziation machen. Domänenmodelle sind ja kaum formalisiert, also könnt ihr da durchaus erklärende Elemente hinzufügen für ein besseres Verständnis.

Es geht bei eurem deskriptiven Modell nicht darum, was man automatisieren könnte, sondern wie die IST-Situation ist, also was macht der Betreiber alles, um die festgestellten Werte zu verbessern. Ob und wie man dass dann automatisieren könnte, kommt später ;).

Für euer präskriptives Domänenmodell würde ich schon empfehlen, die gesamte mögliche Automatisierung darzustellen, aber dann den Bereich markieren, welcher Teil eures funktionalen Prototyps sein wird.

**Comment by annegermund** [comment]
Super, wir haben dann jetzt noch die Version mit Anmerkungen hochgeladen 👍🏻 Falls in den Anmerkungen nur ein Hinweis für einen Fall angegeben ist (z.B. Wert zu hoch), liegt es daran, dass der andere Fall normalerweise nicht eintreten kann. Das würden wir dann in den Foliennotizen noch weiter ausführen.

Im gleichen Wiki-Kapitel haben wir eben das präskriptive Domänenmodell eingefügt. Vielleicht könntest du dir das auch einmal anschauen und uns eine Rückmeldung geben, ob alles soweit verständlich ist? Es ist sehr umfangreich geworden 😁

**Comment by mariofaske** [comment]
Das präskriptive DM ist natürlich nur eine erste Idee, also legt euch da noch nicht fest. Wer weiß ob es zum Beispiel wirklich ein Raspberry wird. Aber ich verstehe es soweit ;)

**Comment by annegermund** [comment]
Alles klar, dann iterieren wir an der Stelle nochmal 👍🏻 Danke für das Feedback!
