### ISSUE TITLE
Foliennotizen

### ISSUE THREAD

**Issue by annegermund** [verenaheissbach/EPWS2122GermundHeissbach#16]
Hallo Mario,

ist es im Foliensatz notwendig, jede Folie anhand der Foliennotizen zu kommentieren? Zum Teil erklären sich die Inhalte bereits von selbst, sodass zusätzliche Kommentare diese hauptsächlich wiederholen würden. Die Erläuterungen ergeben sich bei uns dann im Zusammenspiel aus Folieninhalt und Foliennotizen. Wäre das so in Ordnung?

**Comment by mariofaske** [comment]
Hallo Anne,

Begründungen/Entscheidungen/etc. sollten in die Notizen. Es geht also nicht primär um das Erläutern der Folie, sondern der jeweiligen Artefakte, sprich, wie seid ihr darauf gekommen, welche Abwägungen, Entscheidungen, Abgrenzungen und so weiter führten zu "diesem" Artefakt.

**Comment by annegermund** [comment]
Alles klar, vielen Dank! 👍🏻
