### ISSUE TITLE
Vorführung Rapid Prototype

### ISSUE THREAD

**Issue by verenaheissbach** [verenaheissbach/EPWS2122GermundHeissbach#35]
Hallo Zusammen,
wir planen gerade die Vorführung des Prototypen für das 3. Audit und haben uns gefragt, ob es möglich ist noch zusätzlich mit einem Handy in das Zoom Meeting zu kommen?
Mit dem Handy wollen wir dann den Raspberry Pi, die Sensoren und Relais filmen (zur besseren Darstellung bzw. zum besseren Verständnis des Prototypen).

Vielen Dank im voraus :)

**Comment by vschaefer** [comment]
Das sollte aus meiner Sicht kein Problem sein. Ihr könnte euch ja mal einen eigenen Zoom Raum erstellen und euer Setup dort einmal testen.

**Comment by mariofaske** [comment]
Yo, passt!

**Comment by annegermund** [comment]
Alles klar, machen wir :-) Danke!
