### ISSUE TITLE
Anwendungsfalldiagramm | 3. Audit

### ISSUE THREAD

**Issue by annegermund** [verenaheissbach/EPWS2122GermundHeissbach#36]
Hallo zusammen,

wir würden gerne Use Cases zur Veranschaulichung der Systemfunktionen erstellen, sind hierbei aber auf ein paar Schwierigkeiten gestoßen. Da ein Großteil der Funktionen vom Raspberry Pi automatisch ausgeführt wird (Sensordatenabruf, -verarbeitung, Benachrichtigung, Wasserstand korrigieren), gibt es für den User eigentlich nur zwei Anwendungsfälle: einmal das Einsehen der Sensordaten vor Ort über das Raspi-Display und auf der anderen Seite das Einsehen der Daten "remote". Sollen im Anwendungsfalldiagramm dann nur diese beiden Anwendungsfälle modelliert werden oder schließen wir dabei auch die Aktivitäten des Raspis mit ein? Oder wäre eine alternative Modellierung für uns sinnvoller?

Vielen Dank im Voraus :-)

**Comment by mariofaske** [comment]
Hallo,

schließt auf jeden Fall auch die Aktivitäten des Raspberry mit ein.
