### ISSUE TITLE
Wissenschaftliches Poster, Audit 4

### ISSUE THREAD

**Issue by verenaheissbach** [verenaheissbach/EPWS2122GermundHeissbach#46]
Hallo Mario und Volker,
wir sind gerade im Endspurt unseres Projektes und fragen uns, was genau alles auf das wissenschaftliches Poster soll?
Wir haben ja in dem Sinne keine wissenschaftliche Arbeit betrieben, sollen wir den Prozess des Projektes beschreiben bzw. welche Methoden sollten beschrieben werden?

Und müssen wir fürs 4. Audit auch eine PowerPoint Präsentation erstellen?

Viele Grüße
Anne und Verena

**Comment by mariofaske** [comment]
Hallo,

im Modulwiki unter Poster findet ihr zum einen die gestalterischen Vorgaben und den groben Rahmen des Inhaltes. Ihr seid dahingehend frei, welche Fachkonzepte und Prozesse ihr auf dem Poster präsentieren wollt.

Auch für das 4. Audit müsst ihr einen Foliensatz, ähnlich der vorangegangenen Audits, erstellen und abgeben.

**Comment by verenaheissbach** [comment]
Hallo Mario Danke für deine Antwort. 
Die Vorgaben und den groben Rahmen hatten wir uns schon angesehen. 
Wir sind uns nur unsicher mit den Prozessen, auf den Beispiel Seiten wird mit wissenschaftlichen Methoden gearbeitet, die hatten wir jetzt nicht wirklich. Reichen dann unsere Anwendungsmethoden und Prozesse aus?

Viele Grüße
Anne& Verena

**Comment by mariofaske** [comment]
Ja.

**Comment by verenaheissbach** [comment]
Super. Danke :)
